CREATE TABLE [dbo].[Profile]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ObjectIdentifier] NVARCHAR(36) NOT NULL, 
    [Name] NVARCHAR(128) NOT NULL, 
    [Bio] TEXT NULL,
    [ImageUrl] TEXT NULL, 
    [Email] NVARCHAR(256) NOT NULL, 
    [DateCreated] DATETIME2 NOT NULL DEFAULT GETUTCDATE(), 
    [DateUpdated] DATETIME2 NOT NULL DEFAULT GETUTCDATE(), 
    [HasNotification] BIT NOT NULL DEFAULT 0, 
)
